application: strong-shelter-604
version: 1
runtime: python27
api_version: 1
threadsafe: no

#default_expiration: "30d"

builtins:
- remote_api: on

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: main.APP
# Admin Interface
- url: /.*
  script: warm-up.APP


libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0